CREATE TABLE Carre (Id_carre int NOT NULL IDENTITY(1, 1), PRIMARY KEY (Id_carre));
CREATE TABLE Categorie (Id_categorie int NOT NULL IDENTITY(1, 1), RecetteId_Recette int NOT NULL, Nom varchar(255) NULL, PRIMARY KEY (Id_categorie));
CREATE TABLE Commande (Id_commande int NOT NULL IDENTITY(1, 1), TableId_table int NULL, RecetteId_Recette int NOT NULL, RecetteId_Recette2 int NOT NULL, PRIMARY KEY (Id_commande));
CREATE TABLE Couvert (Id_couvert int NOT NULL IDENTITY(1, 1), Nom int NULL, PRIMARY KEY (Id_couvert));
CREATE TABLE Couvert_Etat (CouvertId_couvert int NOT NULL, EtatId_etat int NOT NULL, Quantite int NULL, PRIMARY KEY (CouvertId_couvert, EtatId_etat));
CREATE TABLE Etat (Id_etat int NOT NULL IDENTITY(1, 1), Nom varchar(255) NULL, PRIMARY KEY (Id_etat));
CREATE TABLE Ingredient (Id_ingredient int NOT NULL IDENTITY(1, 1), Nom varchar(255) NULL, PRIMARY KEY (Id_ingredient));
CREATE TABLE Plat_stocker (Id_plat_stocker int NOT NULL IDENTITY(1, 1), RecetteId_Recette int NOT NULL, Nombre_de_part int NULL, PRIMARY KEY (Id_plat_stocker));
CREATE TABLE Recette (Id_Recette int NOT NULL IDENTITY(1, 1), Nom varchar(255) NULL, Nombre_part int NULL, Tps_preparation int NULL, Tps_cuisson int NULL, Tps_repos int NULL, Disponibilite binary(1) NULL, PRIMARY KEY (Id_Recette));
CREATE TABLE Recette_Ingredient (RecetteId_Recette int NOT NULL, IngredientId_ingredient int NOT NULL, Quantité int NULL, PRIMARY KEY (RecetteId_Recette, IngredientId_ingredient));
CREATE TABLE Recette_Ustensile (RecetteId_Recette int NOT NULL, UstensileId_ustensile int NOT NULL, PRIMARY KEY (RecetteId_Recette, UstensileId_ustensile));
CREATE TABLE Stock (IngredientId_ingredient int NOT NULL, TypeId_type int NOT NULL, Quantite int NULL, PRIMARY KEY (IngredientId_ingredient, TypeId_type));
CREATE TABLE [Table] (Id_table int NOT NULL IDENTITY(1, 1), CarreId_carre int NULL, Nombre_place int NOT NULL, PRIMARY KEY (Id_table));
CREATE TABLE [Type] (Id_type int NOT NULL IDENTITY(1, 1), Nom varchar(255) NULL, PRIMARY KEY (Id_type));
CREATE TABLE Ustensile (Id_ustensile int NOT NULL IDENTITY(1, 1), Nom varchar(255) NULL, PRIMARY KEY (Id_ustensile));
CREATE TABLE Ustensile_Etat (UstensileId_ustensile int NOT NULL, EtatId_etat int NOT NULL, Quantite int NULL, PRIMARY KEY (UstensileId_ustensile, EtatId_etat));
ALTER TABLE [Table] ADD CONSTRAINT FKTable821428 FOREIGN KEY (CarreId_carre) REFERENCES Carre (Id_carre);
ALTER TABLE Commande ADD CONSTRAINT FKCommande576355 FOREIGN KEY (TableId_table) REFERENCES [Table] (Id_table);
ALTER TABLE Recette_Ingredient ADD CONSTRAINT FKRecette_In285547 FOREIGN KEY (IngredientId_ingredient) REFERENCES Ingredient (Id_ingredient);
ALTER TABLE Stock ADD CONSTRAINT FKStock943449 FOREIGN KEY (IngredientId_ingredient) REFERENCES Ingredient (Id_ingredient);
ALTER TABLE Stock ADD CONSTRAINT FKStock768003 FOREIGN KEY (TypeId_type) REFERENCES Type (Id_type);
ALTER TABLE Couvert_Etat ADD CONSTRAINT FKCouvert_Et678546 FOREIGN KEY (CouvertId_couvert) REFERENCES Couvert (Id_couvert);
ALTER TABLE Couvert_Etat ADD CONSTRAINT FKCouvert_Et639567 FOREIGN KEY (EtatId_etat) REFERENCES Etat (Id_etat);
ALTER TABLE Recette_Ustensile ADD CONSTRAINT FKRecette_Us846910 FOREIGN KEY (UstensileId_ustensile) REFERENCES Ustensile (Id_ustensile);
ALTER TABLE Ustensile_Etat ADD CONSTRAINT FKUstensile_695243 FOREIGN KEY (UstensileId_ustensile) REFERENCES Ustensile (Id_ustensile);
ALTER TABLE Ustensile_Etat ADD CONSTRAINT FKUstensile_481332 FOREIGN KEY (EtatId_etat) REFERENCES Etat (Id_etat);
ALTER TABLE Recette_Ingredient ADD CONSTRAINT FKRecette_In355828 FOREIGN KEY (RecetteId_Recette) REFERENCES Recette (Id_Recette);
ALTER TABLE Categorie ADD CONSTRAINT FKCategorie501043 FOREIGN KEY (RecetteId_Recette) REFERENCES Recette (Id_Recette);
ALTER TABLE Plat_stocker ADD CONSTRAINT FKPlat_stock372253 FOREIGN KEY (RecetteId_Recette) REFERENCES Recette (Id_Recette);
ALTER TABLE Recette_Ustensile ADD CONSTRAINT FKRecette_Us618587 FOREIGN KEY (RecetteId_Recette) REFERENCES Recette (Id_Recette);
ALTER TABLE Commande ADD CONSTRAINT FKCommande715515 FOREIGN KEY (RecetteId_Recette2) REFERENCES Recette (Id_Recette);
